services:
  - type: web
    name: ecommerce-shop
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
databases:
  - name: ecommerce_db
    plan: free